### ISSUE TITLE
Serializable rules with an example ? And support Functions etc ?

### ISSUE THREAD

**Issue by iangregsondev** [elite-libs/rules-machine#4]
Hi,

I came across this library and it looks like its just what I need, I found some other previously but they was either not typescript or didn't support serializing the rules and if they did support serializing then you could use any functions as part of the ruleset as underneath it was using js EVAL.

I was wondering if yours support serializing ? I notice its on your list.

Do you have an example ?

And also does it serialize all the rules and any functions part of the rule ?

I would like to store it in a database

Thanks in advance.

**Comment by chhatch** [comment]
Are you looking for something like this?
```
import { ruleFactory } from '@elite-libs/rules-machine';

//get these from your db
const serializedFishRules = JSON.stringify([
  {if: 'fish == "oneFish"', then: 'fish = "twoFish"' },
  {if: 'fish == "redFish"', then: 'fish = "blueFish"' },
])

const fishRules = JSON.parse(serializedFishRules)
const fishRhyme = ruleFactory(fishRules);
// Equivalent to:
// if (fish == "oneFish") fish = "twoFish"
// if (fish == "redFish") fish = "blueFish"

fishyRhyme({fish: 'oneFish'}); // {fish: 'twoFish'}
```

**Comment by justsml** [comment]
Hi @iangregsondev - sorry for the delay.

I specifically didn't want to support serializing arbitrary functions themselves. (Mostly due to security risks.)

That said, the library has an extensible langauge engine. You can [add your own custom functions here.](https://github.com/elite-libs/rules-machine/blob/9aa08eb1ac681ad1036d03098f5a8090c5b3f00a/src/rule-expression-language.ts#L229)

I'm looking at making that file configurable, so each project can have it's own extended behavior.
